[project]
name = "hp3488_ivi"
version = "0.0.1"
authors = [
  { name="Coburn Wightman", email="coburnw@halfstop.top" },
]
description = "Python-IVI driver for the HP 3488A Switch/Control Unit"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/coburnw/hp3488-ivi"